---
# Location where configuration files will be stored.
config_dir: '~'

#
#   This is the Advanced configuration part with extended options.
#   Complete Base configuration in `config.yml` before changing this file.
#   For most cases you are not interested to change this file.
#

#    _____         _ _               
#   |     |___ ___|_| |_ ___ ___ ___ 
#   | | | | . |   | |  _| . |  _|_ -|
#   |_|_|_|___|_|_|_|_| |___|_| |___|
# Advanced Raspberry-monitoring configuration.

# All parameters below require `monitoring_enable` to be `true` in `config.yml`.

monitoring_grafana_public_dashboard: false      # Enable public dashboard for Grafana available in internet

telegram_bot_chatid: "-508236451"               # Used for sending notifications to Telegram bot !Change this token!
telegram_bot_token: "5705452771:AAEPOxb7_rSQZ8p4sZYzITBFqD3YvMs_O-e"  # Used for sending notifications to Telegram bot !Change this token!

monitoring_ping_hosts:                          # [URL];[HUMAN_READABLE_NAME]
  - http://google.com/;google.com
  - https://apple.com/;apple.com
  - https://github.com/;github
  - https://reddit.com/;reddit

# Advanced AirGradient monitoring configuration.
airgradient_sensors:
  # ID is limited in set of "a-z" to not longer than 38 chars.
  # AirGradient FW example ./files/AirGradient-DIY.ino
  - id: livingroom
    ip: "192.168.88.6"
    port: 9926
